name: angular testing

on:
  [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run testing
      continue-on-error: true
      run: |
        npm config set unsafe-perm true
        npm install -g @angular/cli 
        npm install @angular-devkit/build-angular@latest
        npm install
        ng test --code-coverage  --browsers ChromeHeadless 
        npm config set user 0
        npm config set unsafe-perm true
    - name: upload code-cov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        verbose: true # optional (default = false)
        directory: ./coverage/
